# Generated by Django 4.2.5 on 2023-09-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hngapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
